#ifndef Constant_Keys_h
#define Constant_Keys_h

#include "defines.pch"

#define OCAPI_ERROR_DOMAIN @"com.ecn.orange-cloud"

// Help Tips
#define TIP_ZONE_DISMISS       @"dismiss_zone"
#define TIP_ZONE_OPTIONS       @"zone_options"

// Notification keys
#define NOTIF_KEYS_LOADED @"🔑"
#define NOTIF_DISMISS_ZONE @"📕"
#define NOTIF_RELOAD_ZONES @"🐝"
#define NOTIF_DNS_TIMEFRAME_CHANGED @"🦀"
#define NOTIF_FAVICON_CHANGED @"💕"

// DNS Record Types
#define DNS_RECORD_TYPE_A @"A"
#define DNS_RECORD_TYPE_AAAA @"AAAA"
#define DNS_RECORD_TYPE_CNAME @"CNAME"
#define DNS_RECORD_TYPE_LOC @"LOC"
#define DNS_RECORD_TYPE_MX @"MX"
#define DNS_RECORD_TYPE_NS @"NS"
#define DNS_RECORD_TYPE_SPF @"SPF"
#define DNS_RECORD_TYPE_SRV @"SRV"
#define DNS_RECORD_TYPE_TXT @"TXT"
#define DNS_RECORD_TYPE_CAA @"CAA"
#define DNS_RECORD_TYPE_PTR @"PTR"
#define DNS_RECORD_TYPE_CERT @"CERT"
#define DNS_RECORD_TYPE_DNSKEY @"DNSKEY"
#define DNS_RECORD_TYPE_DS @"DS"
#define DNS_RECORD_TYPE_NAPTR @"NAPTR"
#define DNS_RECORD_TYPE_SMIMEA @"SMIMEA"
#define DNS_RECORD_TYPE_SSHFP @"SSHFP"
#define DNS_RECORD_TYPE_TLSA @"TLSA"
#define DNS_RECORD_TYPE_URI @"URI"
#define SUPPORTED_RECORD_TYPES @[DNS_RECORD_TYPE_A, DNS_RECORD_TYPE_AAAA, DNS_RECORD_TYPE_CNAME, DNS_RECORD_TYPE_LOC, DNS_RECORD_TYPE_MX, DNS_RECORD_TYPE_NS, DNS_RECORD_TYPE_SPF,DNS_RECORD_TYPE_SRV, DNS_RECORD_TYPE_TXT, DNS_RECORD_TYPE_CAA, DNS_RECORD_TYPE_PTR, DNS_RECORD_TYPE_CERT, DNS_RECORD_TYPE_DNSKEY, DNS_RECORD_TYPE_DS, DNS_RECORD_TYPE_NAPTR, DNS_RECORD_TYPE_SMIMEA, DNS_RECORD_TYPE_SSHFP, DNS_RECORD_TYPE_TLSA, DNS_RECORD_TYPE_URI]

#define FAVICON_DIRECTORY documents_path(@"favicons")

// Storyboards
#define STORYBOARD_MAIN @"Main"
#define STORYBOARD_ANALYTICS @"Analytics"
#define STORYBOARD_DNS @"DNS"
#define STORYBOARD_FEATURES @"Features"
#define STORYBOARD_LAUNCH @"Launch Screen"
#define STORYBOARD_MORE @"More"
#define STORYBOARD_RULES @"Rules"
#define STORYBOARD_DOMAIN_REGISTRATION @"Domain Registration"

#endif
